version: "3"

services:
  
  mariadb:
    build: "./db"
    environment:
      MYSQL_DATABASE: "boxinator"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "boxinator_test"
      MYSQL_PASSWORD: "boxinator_test"
    tmpfs:
      - "/var/lib/mysql"
  api:
    build: "./api"
    environment:
      SPRING_PROFILES_ACTIVE: "test"
    volumes:
      - "static-files:/src/src/main/resources/static"
    ports:
      - "8080:8080"

  web:
    build: "./web"
    volumes:
      - "static-files:/src/dist"

volumes:
  static-files:
