version: "3"

services:
  
  mariadb:
    build: "./db"
    environment:
      MYSQL_DATABASE: "boxinator"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "boxinator_test"
      MYSQL_PASSWORD: "boxinator_test"
    tmpfs:
      - "/var/lib/mysql"
  api:
    build: "./api"
    volumes:
      - "static-files:/src/src/main/resources/static"
    ports:
      - "8080:8080"

  web:
    build: "./web"
    volumes:
      - "static-files:/src/dist"
  
  cypress:
    image: "cypress/included:3.6.1"
    environment:
      - CYPRESS_baseUrl=http://api:8080
    working_dir: /e2e
    volumes:
      - ./test:/e2e
    entrypoint: sleep infinity

  devenv:
    build: "./devenv"
    volumes:
      - ./:/src
    command: sleep infinity

volumes:
  static-files:
